---
#  Hadoop  base setup

# - name: clean up Hadoop basics
#   become: true
#   file: path={{ item }} state=absent
#   with_items:
#     - /usr/src/hadoop
#     - /usr/src/hadoop-3.0.0
#     - /var/lib/hadoop
#     - /usr/src/hadoop-3.0.0.tar.gz
#     - /etc/profile.d/hadoop.sh
#   tags: clean

- name: check hadoop.tgz
  stat: path=/usr/src/hadoop-3.0.0.tar.gz
  register: hadoop_tgz

- name: check hadoop
  stat: path=/usr/src/hadoop-3.0.0
  register: hadoop_home

- name: download Hadoop
  become: true
  get_url:
    url: http://ftp.jaist.ac.jp/pub/apache/hadoop/common/hadoop-3.0.0/hadoop-3.0.0.tar.gz
    dest: /usr/src/hadoop-3.0.0.tar.gz
  when: not hadoop_tgz.stat.exists

- name: extract Hadoop
  become: true
  command: tar zxvf /usr/src/hadoop-3.0.0.tar.gz -C /usr/src
  when: not hadoop_home.stat.exists

- name: add HADOOP_HOME to envinroment
  become: true
  template: src=etc/profile.d/hadoop.sh dest=/etc/profile.d/hadoop.sh owner=root group=root mode=0644

- name: directories
  become: true
  file: path={{ item }} state=directory owner=hadoop group=hadoop mode=0755
  with_items:
    - /usr/src/hadoop-3.0.0/logs
    - /var/lib/hadoop
    - /var/lib/hadoop/hdfs

- name: copy config files
  become: true
  template: src={{ item }} dest=/usr/src/hadoop-3.0.0/{{ item }} owner=root group=root mode=0644
  with_items:
    - etc/hadoop/core-site.xml
    - etc/hadoop/hdfs-site.xml
    - etc/hadoop/hadoop-env.sh
    - etc/hadoop/mapred-site.xml
    - etc/hadoop/yarn-site.xml
    - etc/hadoop/yarn-env.sh
