
# - name: clean up
#   become: true
#   file: path={{ item }} state=absent
#   with_items:
#     - /usr/src/hadoop
#     - /usr/src/hadoop-2.9.0
#     - /var/lib/hadoop
#     - /tmp/hadoop
#     - /tmp/hadoop-2.9.0.tar.gz

# Hadoop  base setup
- name: check hadoop.tgz
  stat: path=/tmp/hadoop-2.9.0.tar.gz
  register: hadoop_tgz

- name: check hadoop
  stat: path=/usr/src/hadoop-2.9.0
  register: hadoop_home

- name: download Hadoop
  get_url:
    url:  http://ftp.jaist.ac.jp/pub/apache/hadoop/common/hadoop-2.9.0/hadoop-2.9.0.tar.gz
    dest: /tmp/hadoop-2.9.0.tar.gz
  when: not hadoop_tgz.stat.exists

- name: extract Hadoop
  become: true
  command: tar zxvf /tmp/hadoop-2.9.0.tar.gz -C /usr/src
  when: not hadoop_home.stat.exists

- name: directories
  become: true
  file: path={{ item }} state=directory owner=hadoop group=hadoop mode=0755
  with_items:
    - /usr/src/hadoop-2.9.0/logs
    - /var/lib/hadoop
    - /var/lib/hadoop/hdfs

- name: copy config files
  become: true
  template: src={{ item }} dest=/usr/src/hadoop-2.9.0/{{ item }} owner=root group=root mode=0644
  with_items:
    - etc/hadoop/core-site.xml
    - etc/hadoop/hdfs-site.xml
    - etc/hadoop/hadoop-env.sh
    - etc/hadoop/mapred-site.xml
    - etc/hadoop/yarn-site.xml
    - etc/hadoop/yarn-env.sh
