---
- name: apt-get install oracle-java8-jdk, git, sshpass
  become: true
  apt: name={{item}} state=present update_cache=yes
  with_items:
      - oracle-java8-jdk
      - git
      - sshpass

- name: Update '/etc/hosts'
  become: true
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "u=rw,g=r,o=r" # 0644

- name: Update '/etc/hostname'
  become: true
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: "u=rw,g=r,o=r" # 0644

- name: create groups
  become: true
  group: name={{ item.name }} state=present
  with_items: "{{ users }}"

- name: create users
  become: true
  user: name={{ item.name }} shell=/bin/bash state=present group={{ item.name }} append=yes groups={{ item.groups }}
  with_items: "{{ users }}"

- name: change password
  become: true
  user: name={{ item.name }} password={{ item.password }}
  with_items: "{{ users }}"

- name: check ssh-key
  stat: path=/home/pi/.ssh/id_rsa
  register: ssh_key

- name: create ssh-key
  shell: sh -lc "ssh-keygen -f .ssh/id_rsa -t rsa -N ''"
  when: not ssh_key.stat.exists

- name: check generated-ssh-key
  stat: path=/home/pi/.ssh/id_rsa
  register: ssh_key

- name: copy ssh-key to each node
  shell: sh -lc "sshpass -p 'raspberry' ssh-copy-id -i ~/.ssh/id_rsa.pub -o 'StrictHostKeyChecking no' {{ item }}"
  with_items: "{{ ansible_play_hosts }}"
  when: ssh_key.stat.exists
