---
# namenode

# - name: stop service hadoop-namenode
#   become: true
#   service: name=hadoop-namenode enabled=false state=stopped
#   tags: clean
#
# - name: clean up Hadoop namenode
#   become: true
#   file: path={{ item }} state=absent
#   with_items:
#     - /var/lib/hadoop
#     - /etc/systemd/system/hadoop-namenode.service
#   tags: clean

- name: directories
  become: true
  file: path={{ item }} state=directory owner=hadoop group=hadoop mode=0700
  with_items:
    - /var/lib/hadoop/hdfs/namenode

- name: check hdfs namenode
  become: true
  stat: path=/var/lib/hadoop/hdfs/namenode/current
  register: hdfs_namenode

- name: format hdfs namenode
  become: true
  shell: sudo -u hadoop /usr/src/hadoop-3.0.0/bin/hadoop namenode -format
  when: not hdfs_namenode.stat.exists

- name: register systemd services
  become: true
  template: src={{ item }}.service dest=/etc/systemd/system/{{ item }}.service owner=root group=root mode=0644
  with_items:
    - dfs-namenode
    - yarn-namenode

- name: start systemd services
  become: true
  service: name={{item}} enabled=yes state=started
  with_items:
    - dfs-namenode
    - yarn-namenode
