---
# namenode
- name: directories
  become: true
  file: path={{ item }} state=directory owner=hadoop group=hadoop mode=0700
  with_items:
    - /var/lib/hadoop/hdfs/namenode

- name: check hdfs namenode
  become: true
  stat: path=/var/lib/hadoop/hdfs/namenode/current
  register: hdfs_namenode

- name: format hdfs namenode
  become: true
  shell: sudo -u hadoop /usr/src/hadoop-2.9.0/bin/hadoop namenode -format
  when: not hdfs_namenode.stat.exists

- name: systemd hadoop-namenode
  become: true
  template: src={{ item }}.service dest=/etc/systemd/system/{{ item }}.service owner=root group=root mode=0644
  with_items:
    hadoop-namenode

- name: service hadoop-namenode
  become: true
  service: name=hadoop-namenode enabled=yes state=started
